"""0002_add_user_flags

Revision ID: 5b08fc804d28
Revises: 0001_seed
Create Date: 2024-10-04 21:50:15.456470

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5b08fc804d28"
down_revision: Union[str, None, tuple] = "72112e6a6208"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("hashed_password", sa.Text(), nullable=False))
    op.add_column("users", sa.Column("is_superuser", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.drop_column("users", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("password", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.drop_column("users", "is_active")
    op.drop_column("users", "is_superuser")
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
