"""added foreign keys

Revision ID: 0ac3725aff2d
Revises: 19b5a4f199b9
Create Date: 2024-09-20 23:17:14.274828

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0ac3725aff2d"
down_revision: Union[str, None] = "19b5a4f199b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "permissions", sa.Column("role_uuid", sa.UUID(), nullable=True)
    )
    op.create_unique_constraint(None, "permissions", ["role_uuid"])
    op.create_foreign_key(
        None,
        "permissions",
        "roles",
        ["role_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.add_column("roles", sa.Column("user_uuid", sa.UUID(), nullable=True))
    op.create_unique_constraint(None, "roles", ["user_uuid"])
    op.create_foreign_key(
        None, "roles", "users", ["user_uuid"], ["uuid"], ondelete="CASCADE"
    )
    op.alter_column(
        "users",
        "nickname",
        existing_type=sa.VARCHAR(),
        comment="",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "first_name",
        existing_type=sa.VARCHAR(),
        comment="",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "last_name",
        existing_type=sa.VARCHAR(),
        comment="",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "patronymic",
        existing_type=sa.VARCHAR(),
        comment="",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "patronymic",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "last_name",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "first_name",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "nickname",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="",
        existing_nullable=True,
    )
    op.drop_constraint(None, "roles", type_="foreignkey")
    op.drop_constraint(None, "roles", type_="unique")
    op.drop_column("roles", "user_uuid")
    op.drop_constraint(None, "permissions", type_="foreignkey")
    op.drop_constraint(None, "permissions", type_="unique")
    op.drop_column("permissions", "role_uuid")
    # ### end Alembic commands ###
